Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FileName:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
