require 'aws-sdk-cloudsearchdomain'

require 'nazrin/searchable'
require 'nazrin/data_accessor'
require 'nazrin/config'
require 'nazrin/search_client'
require 'nazrin/document_client'
require 'nazrin/pagination_generator'
require 'nazrin/paginated_array'
require 'nazrin/version'
